/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectostratego.utilidades;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class jframe extends javax.swing.JDialog { 

    /**
     * Creates new form jframe
     */
    public jframe(java.awt.Frame parent, boolean modal) {
    super(parent, modal);  // Configura el diálogo como modal
    initComponents();
    this.setResizable(false);
    this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // Evita que se cierre con la X
    
    
    
}
    //108 , 89
    
    
    
    
    public void setPieza1(Piezas pieza)
    {
    this.NombrePiezaSeleccionada.setText(pieza.nombre);
    this.Pieza1Foto.setIcon(new ImageIcon(pieza.imagenVs));
    }
    
    public void setPieza2(Piezas pieza)
    {
    this.NombreObjetivo.setText(pieza.nombre);
    this.Pieza2Foto.setIcon(new ImageIcon(pieza.imagenVs));
    }
    
    public void setGanador(Piezas pieza)
    {
    this.Ganador.setText(pieza.nombre);
    }
    
    public void setForm(Piezas pieza1 ,Piezas pieza2, Piezas ganador)
    {
    setPieza1(pieza1);
    setPieza2(pieza2);
    setGanador(ganador);
    Timer timer = new Timer(3000, e -> dispose()); // 3 segundos
timer.setRepeats(false);
timer.start();
    
    }
    
    public void setEmpate(Piezas pieza1 , Piezas pieza2)
    {
    setPieza1(pieza1);
    setPieza2(pieza2);
    this.Ganador.setText("EMPATE");
    this.jLabel4.setText("");
    Timer timer = new Timer(3000, e -> dispose()); // 3 segundos
timer.setRepeats(false);
timer.start();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombrePiezaSeleccionada = new javax.swing.JLabel();
        NombreObjetivo = new javax.swing.JLabel();
        Pieza2Foto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ganador = new javax.swing.JLabel();
        Pieza1Foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("VS");

        NombrePiezaSeleccionada.setText("NOMBRE PIEZA");

        NombreObjetivo.setText("NOMBRE OBJETIVO");

        jLabel4.setText("HA GANADO:");

        Ganador.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombrePiezaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pieza1Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pieza2Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pieza2Foto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pieza1Foto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NombrePiezaSeleccionada)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Ganador))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NombreObjetivo)
                        .addGap(82, 82, 82))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    // ... código existente ...
    
    // Modifica la creación de la ventana
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new jframe(null, true).setVisible(true); // Modal=true
        }
    });
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ganador;
    private javax.swing.JLabel NombreObjetivo;
    private javax.swing.JLabel NombrePiezaSeleccionada;
    private javax.swing.JLabel Pieza1Foto;
    private javax.swing.JLabel Pieza2Foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
